version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitor_network
  grafana:
    image: grafana/grafana:8.5.22
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
    depends_on:
      - prometheus
    restart: always
    networks:
      - monitor_network
volumes:
  grafana-data:
  grafana-config:
networks:
  monitor_network:
    driver: bridge